"""Public catalog and thresholds for analyser pattern signals."""

from .patterns import (
    RULE_CATALOG, EXPLORATION_CALL_THRESHOLD, SESSION_DURATION_SECONDS_THRESHOLD,
    SESSION_WORK_TOKEN_THRESHOLD, LARGE_OUTPUT_CHAR_THRESHOLD,
    SUBAGENT_SPAWN_THRESHOLD,
)

__all__ = ["RULE_CATALOG", "EXPLORATION_CALL_THRESHOLD", "SESSION_DURATION_SECONDS_THRESHOLD", "SESSION_WORK_TOKEN_THRESHOLD", "LARGE_OUTPUT_CHAR_THRESHOLD", "SUBAGENT_SPAWN_THRESHOLD"]
